### PR TITLE
exchange XML cleaning

### PR DESCRIPTION
**Pull request by marawilhelmi**
deleted Pub2tei script and added Martinos XML text extraction script

### CODE REVIEW

**Comment by vgvinter** [comment]
@kjappelbaum maybe you can close this PR?

the typos are already fixed, the only thing left is perhaps to place the XLM code in a dropdown, as you suggested, but it is not essential

**Comment by kjappelbaum** [comment]
There is a merge conflict, I can try to look into it a bit later

**Comment by kjappelbaum** [comment]
I'm a bit torn about merging it into the current state. All of the code below could benefit from more context. The good thing about `Pub2Tei` was that it is reusable. For the code below, it is not super clear. I feel we should make clearer what parts are specific and what parts are reusable. 


```
from bs4 import BeautifulSoup as bs
import re
import json


# Function to extract non-empty child elements of a given element
def extract_children(element):
    children = []
    for child in element.children:
        # Check if the child element has a name or non-empty string content
        if child.name is not None or child.string.strip() != "":
            children.append(child)

    # Raise an error if the element has no valid children
    if len(children) < 1:
        raise ValueError("ce:section should not be empty")
    else:
        return children


# Function to check if an element's name matches the given name
def element_name(element, name):
    if ":" in name:
        prefix, node_name = name.split(":")
        return element.prefix == prefix and element.name == node_name
    else:
        return element.name == name


# Function to remove newline characters from a text string
def remove_newlines(text):
    return text.replace("\n", " ")


# Function to extract and clean paragraph elements' text
def extract_para_elements(element):
    return re.sub(" +", " ", remove_newlines(element.text))


# Function to extract section elements and their contents recursively
def extract_section_elements(element):
    paragraphs = []
    for child in extract_children(element):
        if element_name(child, "ce:label"):
            pass
        elif element_name(child, "ce:section-title"):
            title = child.text
        elif element_name(child, "ce:para"):
            paragraphs.append(extract_para_elements(child))
        elif element_name(child, "ce:section"):
            paragraphs.append(extract_section_elements(child))
        else:
            print(child)
            raise ValueError("Expecting no other section type")

    return {title: paragraphs}


# Function to extract text from sections in the BeautifulSoup object
def extract_sections_text(soup):
    sections = soup.find("ce:sections")
    if sections is not None:
        sections_content = []
        for child in extract_children(sections):
            if element_name(child, "ce:section"):
                if len(child) < 1:
                    raise ValueError("section must not be empty")
                sections_content.append(extract_section_elements(child))
            else:
                raise ValueError(
                    f'Expecting different section name. Obtained: "{child.name}". Expecting: "section".'
                )
    return sections_content


# Open and read the XML file
with open("XML_files/S0022286012008502.xml", "r") as f:
    file = f.read()

# 'xml' is the parser used. For HTML files, which BeautifulSoup is typically used for, it would be 'html.parser'.
soup = bs(file, "lxml-xml")
f.close()

# Extract sections text from the parsed XML
zz = extract_sections_text(soup)

# Print the extracted text
print(zz)

# Save the extracted text into a json file
with open("output.json", "w") as json_file:
    json.dump(zz, json_file, indent=4)
```

**Comment by vgvinter** [comment]
okay, this is not clear to me, do you want to remove the `Pub2TEI` code that is now in the notebook and leave only the text extraction once you have the converted XML?

in any case, for the extraction part, do you think something like this could work? it explains how to use the different functions step by step (it could be extended maybe), and I'm assuming they are all reusable:


Many APIs return the articles directly in machine-readable XML format. However, the ones of different publishers are quite different, which can make this kind of cleanup tedious. Thus, it is great that there are packages such as `Pub2TEI` that can help one to streamline this process. Afterward one could extract the text contained in the formatted XML file and save it in a easy accessible and readable `JSON` file.

---here would be the code for the use of Pub2TEI if kept---

To extract the text contained in the formatted XML file and save it in a `JSON` file, we can use the code shown below.

```
from bs4 import BeautifulSoup as bs
import re
import json

# Open and read the formatted XML file 
with open("XML_files/S0022286012008502.xml", "r") as f:
    file = f.read()
    
# Use BeautifulSoup to extract the text, where 'xml' is the parser used for XML files. For HTML files, you can use 'html.parser'.
soup = bs(file, "lxml-xml")
f.close()
```

Once we have the BeautifulSoup object, we can extract the text of the article. For that, we could use the function `extract_sections_text`.

```
# Extract text by sections from the parsed XML
zz = extract_sections_text(soup)

# Function to extract text by sections from the BeautifulSoup object
def extract_sections_text(soup):
    sections = soup.find("ce:sections")
    if sections is not None:
        sections_content = []
        for child in extract_children(sections):
            if element_name(child, "ce:section"):
                if len(child) < 1:
                    raise ValueError("section must not be empty")
                sections_content.append(extract_section_elements(child))
            else:
                raise ValueError(
                    f'Expecting different section name. Obtained: "{child.name}". Expecting: "section".'
                )
    return sections_content
```

This function requires the use of some other functions shown here.

```
# Function to extract non-empty child elements of a given element
def extract_children(element):
    children = []
    for child in element.children:
        # Check if the child element has a name or non-empty string content
        if child.name is not None or child.string.strip() != "":
            children.append(child)

    # Raise an error if the element has no valid children
    if len(children) < 1:
        raise ValueError("ce:section should not be empty")
    else:
        return children

# Function to check if an element's name matches the given name
def element_name(element, name):
    if ":" in name:
        prefix, node_name = name.split(":")
        return element.prefix == prefix and element.name == node_name
    else:
        return element.name == name
    
# Function to remove newline characters from a text string
def remove_newlines(text):
    return text.replace("\n", " ")
    
# Function to extract and clean paragraph elements' text
def extract_para_elements(element):
    return re.sub(" +", " ", remove_newlines(element.text))

# Function to extract section elements and their content recursively
def extract_section_elements(element):
    paragraphs = []
    for child in extract_children(element):
        if element_name(child, "ce:label"):
            pass
        elif element_name(child, "ce:section-title"):
            title = child.text
        elif element_name(child, "ce:para"):
            paragraphs.append(extract_para_elements(child))
        elif element_name(child, "ce:section"):
            paragraphs.append(extract_section_elements(child))
        else:
            print(child)
            raise ValueError("Expecting no other section type")
    return {title: paragraphs}
```

Once we have the text of the article by sections, we can save the extracted text in a `JSON` file.

```
# Print the extracted text
print(zz)

# Save the extracted text into a JSON file
with open("output.json", "w") as json_file:
    json.dump(zz, json_file, indent=4)
```

One could then add the extracted text easily into the LLM prompt or even delete irrelevant sections quickly.

**Comment by kjappelbaum** [comment]
closing as it has been superseeded

**Pull request closed without merging**
